### PR TITLE
Skip RSS issues while loading preferences and displaying dialogs

### PR DESCRIPTION
**Pull request by theodore-tegos**
The issue with RSS accounts not being visible in the WebExtension Accounts API is causing various problems in Xpunge.

https://phabricator.services.mozilla.com/D218918

It is not just the inconvenience of not seeing RSS accounts (such as "Blogs and News Feeds") in the Xpunge preferences.

If the user had set up any RSS accounts/folders in the MultiXpunge or Timer sections of Xpunge in TB 115:

- That setup will be lost in TB 128

- All Xpunge preferences following an RSS-related one for compacting, are not loaded in the preferences page, including in subsequent tabs. So if the RSS account/folder is in the MultiXpunge compact list, the following preferences are not loaded at all:
  - Remaining compact list entries in the MultiXpunge tab
  - All the preferences in the Timer tab
  - All the preferences in the Settings tab

- If the confirmation dialog settings are enabled in the Settings tab, there are errors when trying to display the dialogs because "account" variables are null.

The changes in this PR aim at skipping these errors, while still allowing the rest of the functionality to work.

### CODE REVIEW

**Comment by theodore-tegos** [comment]
It is better to view the diff in this PR with whitespace hidden.

**Comment by theodore-tegos** [comment]
@jobisoft fyi

**Comment by jobisoft** [comment]
Hi, the fix for the RSS issue has landed in Thunderbird 128.2.0:
https://bugzilla.mozilla.org/show_bug.cgi?id=1912393#c8

You can already update your manifest to request a `strict_min_version` of `128.2.0`. Release of 128.2.0 will happen shortly. I will keep you posted.

**Comment by jobisoft** [comment]
It is time to release :-)

https://www.thunderbird.net/en-US/thunderbird/128.2.0esr/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=128.2.0&channel=esr&os=WINNT&buildid=20240903190455

**Comment by theodore-tegos** [comment]
@jobisoft there is one more issue that I'd like to fix before creating a release for TB 128, cannot wait for a patch version.

If an account/folder that has been added to the "To Be Compacted" list for MultiXpunge/Timer is deleted, it messes up the Xpunge preferences.

**Comment by jobisoft** [comment]
> @jobisoft there is one more issue that I'd like to fix before creating a release for TB 128, cannot wait for a patch version.
> 
> If an account/folder that has been added to MultiXpunge/Timer is deleted, it messes up the Xpunge preferences.

https://github.com/theodore-tegos/xpunge-tb/pull/10

**Pull request merged**
